#PROD environment

app:
  message: This is the property file for the ${spring.application.name}

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: <MYSQL_URL>
    username: <USERNAME>
    password: <PASSWORD>